#!/bin/sh
commit_msg=$(cat $1)
regex="^((major|feat|feature|patch|fix|hotFix|bugFix|chore|docs|revert|refactor):){1}([[:blank:]])+(@([A-Za-z0-9]{1,}))([[:blank:]])+[A-Za-z0-9]{1,}"
COLOR='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color
BOLD=$(tput bold)
NORM=$(tput sgr0)

if ! echo "$commit_msg" | grep -Eq $regex; then
  echo "
  ❌ ${COLOR}${BOLD}Invalid commit message format${NC}${NORM} 😂.
      
      - ${COLOR}${BOLD}correct format${NC}${NORM}:
        '(commitType): @(your name) (your commit message with clear 4 or more words for simple description of your changes)'

      - ${COLOR}${BOLD}example${NC}${NORM}: 
        feature: @carlJohnson Follow The Damn Train, CJ! 

      - ${COLOR}${BOLD}list of commitType${NC}${NORM}:
        major|feat|feature|patch|fix|hotFix|bugFix|chore|docs|revert|refactor

     ❤️  ${COLOR}${BOLD}Please fix your commit${NC}${NORM} 🖕

      your commit message: ${RED}${BOLD}${commit_msg}${NC}${NORM}
     "
  exit 1
fi